### PR TITLE
auto return type for accessors

### LINKED ISSUE #11: Using alias-imported types for fields might cause naming collisions
When using two different types with the same name (one of them imported as an alias) inside a class breaks compilation:

```
import accessors;
import person : PersonId;
import another : AnotherPersonId = PersonId;

class Foo
{
    @ConstRead
    private PersonId personId_;

    @ConstRead
    private AnotherPersonId anotherPersonId_;

    mixin(GenerateFieldAccessors);
}
```

> Error: cannot implicitly convert expression (this.anotherPersonId_) of type const(PersonId) to const(PersonId)

### PR DESCRIPTION
**Pull request by belka-ew**
This is a suggestion to fix #11.

Instead of using a string as the accessor return type, it may be better to use `auto`, so the compiler can infer the return type based on the type of the appropriate class/struct member.

Marking the property as const/inout seems to be enough for the compiler to infer the return type with the correct mutability.

### CODE REVIEW

File: test/main.d [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import accessors;
+
+void main()
+{
+}
+
+// Issue #11: https://github.com/funkwerk/accessors/issues/11
+pure nothrow @safe @nogc unittest
```
Comment (linkrope) [inline test/main.d]: _Attributes should be listed in alphabetical ordering, e.g. `const @nogc nothrow pure @safe` (the ordering should ignore the leading `@`)._

Comment (belka-ew) [reply test/main.d]: fixed.

File: src/accessors.d [hunk 2]
```diff
@@ -84,24 +84,24 @@ template GenerateReader(string name, alias field)
...
 
         static if (isArray!(typeof(field)) && !isSomeString!(typeof(field)))
         {
-            enum valueType = typeName!(MutableOf!(ForeachType!(typeof(field))));
-
-            return format("%s final @property inout(%s)[] %s() inout " ~
-                "{ inout(%s)[] result = null; result ~= this.%s; return result; }",
-                visibility, valueType, accessorName, valueType, name);
+            return format("%s final @property auto %s() inout {"
+                        ~ "import std.traits;"
```
Comment (linkrope) [inline src/accessors.d]: _Local imports should specify the symbols being imported to avoid hiding local symbols._

File: src/accessors.d [hunk 3]
```diff
@@ -84,24 +84,24 @@ template GenerateReader(string name, alias field)
...
+                        ~ "inout(ForeachType!(typeof(this.%s)))[] result = null;"
+                        ~ "return result ~ this.%s;"
```
Comment (linkrope) [inline src/accessors.d]: Is there a more explicit way to copy the array?

**Review by linkrope — CHANGES_REQUESTED** [review]

File: src/accessors.d (hunk 3 above)
Comment (belka-ew) [reply src/accessors.d]: I'm aware only of `.dup`.

Comment (linkrope) [reply src/accessors.d]: try `.dup`; otherwise, try `[] ~ ...`

**Review by linkrope — CHANGES_REQUESTED** [review]

File: src/accessors.d (hunk 3 above)
Comment (belka-ew) [reply src/accessors.d]: .dup:
```
src/accessors.d-mixin-666-mixin-668(668,58): Error: template object.dup cannot deduce function from argument types !()(inout(const(X)[])), candidates are:
/usr/include/dmd/druntime/import/object.d(1943,6):        object.dup(T : V[K], K, V)(T aa)
/usr/include/dmd/druntime/import/object.d(1979,6):        object.dup(T : V[K], K, V)(T* aa)
/usr/include/dmd/druntime/import/object.d(3737,16):        object.dup(T)(T[] a) if (!is(const(T) : T))
/usr/include/dmd/druntime/import/object.d(3753,15):        object.dup(T)(const(T)[] a) if (is(const(T) : T))
src/accessors.d(677,9): Error: static assert  is(typeof(y) == const(X)[]) is false
```

**Review by linkrope — APPROVED** [review]

**Comment by belka-ew** [comment]
ping @duselbaer

**Comment by duselbaer** [comment]
Doesn't solve it for @Write

**Review by duselbaer — APPROVED** [review]
